if (!isDedicated) exitWith {};
diag_log text "BUILDINGS: loading extra buildings...";
call compile preprocessFileLineNumbers "addons\buildings\locations\c130_crash_6200_6850.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\field_hospital_5200_2300.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\nwaf_barracks_camp.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\gas_station_4250_10450.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\neaf_barracks_camp.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\nwaf_barracks_additions.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\hero_bandit_fire_barrels.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\balota_barracks.sqf";
call compile preprocessFileLineNumbers "addons\buildings\locations\air_dealer_barriers.sqf";